import fs from "node:fs";
import vm from "node:vm";
import { SOURCE_REGISTRY } from "../src/source-registry.js";

function loadWindowScript(path, property) {
  const code = fs.readFileSync(path, "utf8");
  const context = { window: {} };
  vm.createContext(context);
  vm.runInContext(code, context, { filename: path });
  return context.window[property];
}

function q(value) {
  if (value === null || value === undefined) return "null";
  return "'" + String(value).replaceAll("'", "''") + "'";
}

function num(value) {
  return Number.isFinite(value) ? String(value) : "null";
}

function textArray(values = []) {
  if (!values.length) return "'{}'::text[]";
  return "ARRAY[" + values.map(q).join(",") + "]::text[]";
}

function bool(value) {
  return value ? "true" : "false";
}

const data = loadWindowScript("public/data.js", "RADAR_DATA");
const signals = loadWindowScript("public/signals.js", "RADAR_SIGNALS");
const partners = loadWindowScript("public/partners.js", "RADAR_PARTNERS");
const scores = loadWindowScript("public/scores.js", "RADAR_SCORES");

const sql = [];
sql.push("-- Generated by scripts/generate-seed.mjs");
sql.push("-- Review before applying to Supabase.");
sql.push("begin;");
sql.push("");

for (const market of data.markets) {
  sql.push(`insert into public.markets (slug, country_code, name, expansion_score, status, summary, tags, last_reviewed_at)
values (${q(market.id)}, ${q(market.code)}, ${q(market.name)}, ${num(market.score)}, ${q(market.status === "live" ? "live" : "research")}, ${q(market.summary)}, ${textArray(market.tags)}, ${q(data.lastReviewed)}::timestamptz)
on conflict (slug) do update set
  country_code = excluded.country_code,
  name = excluded.name,
  expansion_score = excluded.expansion_score,
  status = excluded.status,
  summary = excluded.summary,
  tags = excluded.tags,
  last_reviewed_at = excluded.last_reviewed_at,
  updated_at = now();`);
  sql.push("");
}

for (const market of data.markets) {
  for (const operator of market.operators || []) {
    sql.push(`insert into public.operators (market_id, name, group_name, market_share, rail_summary, confidence, note, last_verified_at)
select id, ${q(operator.name)}, ${q(operator.group)}, ${num(operator.share)}, ${q(operator.rail)}, ${q(operator.confidence)}, ${q(operator.note)}, ${q(data.lastReviewed)}::timestamptz
from public.markets where slug = ${q(market.id)}
on conflict (market_id, name) do update set
  group_name = excluded.group_name,
  market_share = excluded.market_share,
  rail_summary = excluded.rail_summary,
  confidence = excluded.confidence,
  note = excluded.note,
  last_verified_at = excluded.last_verified_at,
  updated_at = now();`);
  }

  for (const rail of market.rails || []) {
    const matchingSource = (market.sources || []).find(s =>
      String(s.label || "").toLowerCase().includes(String(rail.evidence || "").toLowerCase()) ||
      String(rail.evidence || "").toLowerCase().includes(String(s.label || "").toLowerCase())
    );
    sql.push(`insert into public.billing_rails (market_id, provider_name, rail_type, confidence, evidence_summary, source_label, source_url, last_verified_at)
select id, ${q(rail.provider)}, ${q(rail.type)}, ${q(rail.confidence)}, ${q(rail.evidence)}, ${q(matchingSource?.label || rail.evidence)}, ${q(matchingSource?.url || null)}, ${q(data.lastReviewed)}::timestamptz
from public.markets where slug = ${q(market.id)}
on conflict (market_id, provider_name, rail_type) do update set
  confidence = excluded.confidence,
  evidence_summary = excluded.evidence_summary,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  last_verified_at = excluded.last_verified_at,
  updated_at = now();`);
  }

  for (const target of market.ecosystem || []) {
    sql.push(`insert into public.commercial_targets (market_id, company_name, commercial_role, evidence_status, last_verified_at)
select id, ${q(target.company)}, ${q(target.role)}, ${q(target.status)}, ${q(data.lastReviewed)}::timestamptz
from public.markets where slug = ${q(market.id)}
on conflict (market_id, company_name) do update set
  commercial_role = excluded.commercial_role,
  evidence_status = excluded.evidence_status,
  last_verified_at = excluded.last_verified_at,
  updated_at = now();`);
  }

  for (const contact of market.contacts || []) {
    sql.push(`insert into public.contacts (market_id, commercial_target_id, full_name, company_name, title, location, profile_url, source_label, last_verified_at)
select m.id,
       (select ct.id from public.commercial_targets ct where ct.market_id = m.id and ct.company_name = ${q(contact.company)} limit 1),
       ${q(contact.name)}, ${q(contact.company)}, ${q(contact.title)}, ${q(contact.location)}, ${q(contact.url)}, ${q(contact.source)}, ${q(data.lastReviewed)}::timestamptz
from public.markets m where m.slug = ${q(market.id)}
on conflict (market_id, full_name, company_name) do update set
  commercial_target_id = excluded.commercial_target_id,
  title = excluded.title,
  location = excluded.location,
  profile_url = excluded.profile_url,
  source_label = excluded.source_label,
  last_verified_at = excluded.last_verified_at,
  updated_at = now();`);
  }

  const scoreValues = scores.markets?.[market.id] || {};
  for (const component of scores.components || []) {
    const value = scoreValues[component.key];
    if (!Number.isFinite(value)) continue;
    sql.push(`insert into public.market_score_components (market_id, model_version, component_key, label, description, score)
select id, ${q(scores.version)}, ${q(component.key)}, ${q(component.label)}, ${q(component.description)}, ${num(value)}
from public.markets where slug = ${q(market.id)}
on conflict (market_id, model_version, component_key) do update set
  label = excluded.label,
  description = excluded.description,
  score = excluded.score,
  updated_at = now();`);
  }
}

for (const signal of signals) {
  sql.push(`insert into public.market_signals (external_key, market_id, signal_type, confidence, title, summary, company_name, source_label, source_url, observed_at)
select ${q(signal.id)}, id, ${q(signal.type)}, ${q(signal.confidence)}, ${q(signal.title)}, ${q(signal.summary)}, ${q(signal.company)}, ${q(signal.sourceLabel)}, ${q(signal.sourceUrl)}, ${q(signal.observedAt)}::timestamptz
from public.markets where slug = ${q(signal.marketId)}
on conflict (external_key) do update set
  signal_type = excluded.signal_type,
  confidence = excluded.confidence,
  title = excluded.title,
  summary = excluded.summary,
  company_name = excluded.company_name,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  observed_at = excluded.observed_at;`);
}

for (const [id, source] of Object.entries(SOURCE_REGISTRY)) {
  sql.push(`insert into public.market_sources (external_key, market_id, label, url, source_type, monitor_enabled)
select ${q(id)}, id, ${q(source.label)}, ${q(source.url)}, ${q(source.type)}, true
from public.markets where slug = ${q(source.marketId)}
on conflict (external_key) do update set
  market_id = excluded.market_id,
  label = excluded.label,
  url = excluded.url,
  source_type = excluded.source_type,
  monitor_enabled = excluded.monitor_enabled,
  updated_at = now();`);
}

for (const partner of partners) {
  sql.push(`insert into public.payment_partners (slug, name, partner_type, confidence, summary, capabilities, source_label, source_url, last_verified_at)
values (${q(partner.id)}, ${q(partner.name)}, ${q(partner.type)}, ${q(partner.confidence)}, ${q(partner.summary)}, ${textArray(partner.capabilities)}, ${q(partner.currentEvidence?.label)}, ${q(partner.currentEvidence?.url)}, ${q(data.lastReviewed)}::timestamptz)
on conflict (slug) do update set
  name = excluded.name,
  partner_type = excluded.partner_type,
  confidence = excluded.confidence,
  summary = excluded.summary,
  capabilities = excluded.capabilities,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  last_verified_at = excluded.last_verified_at,
  updated_at = now();`);

  for (const route of partner.routes || []) {
    sql.push(`insert into public.payment_partner_routes (partner_id, market_id, operator_scope, route_status, note, evidence_url, last_verified_at)
select p.id, m.id, ${q(route.operator)}, ${q(route.status)}, ${q(route.note)}, ${q(route.evidence)}, ${q(data.lastReviewed)}::timestamptz
from public.payment_partners p
join public.markets m on m.slug = ${q(route.marketId)}
where p.slug = ${q(partner.id)}
on conflict (partner_id, market_id, operator_scope) do update set
  route_status = excluded.route_status,
  note = excluded.note,
  evidence_url = excluded.evidence_url,
  last_verified_at = excluded.last_verified_at,
  updated_at = now();`);
  }
}

sql.push("");
sql.push("commit;");
sql.push("");

process.stdout.write(sql.join("\n"));
